### ISSUE TITLE
Training the DAGMM model

### ISSUE THREAD

**Issue by ajaychawda58** [RomainSabathe/dagmm#2]
I am using the code in this way: 
`compression = CompressionNetwork()`
`estimation = EstimationNetwork()`
`gmm = GMM(2,4)`
`gmm.train()`

But feels like I am missing something to train the model. What is the correct way to train the model?
Please help with this issue. 

Thank you.

**Comment by RomainSabathe** [comment]
Hi, the training happens implicitly as you run samples through a DAGMM network. See [here ](https://github.com/RomainSabathe/dagmm/blob/a3bc1c0a5a95935420c47678aa8931fadddacb5a/model.py#L33) for more details :)

If you're only interested in updating a GMM, then you need to use [_update_mixtures_parameters ](https://github.com/RomainSabathe/dagmm/blob/a3bc1c0a5a95935420c47678aa8931fadddacb5a/gmm.py#L36) manually.

**Comment by ajaychawda58** [comment]
Thank you for your reply. 

Just to confirm that this is the way to train the model.

`compression = CompressionNetwork(train_data.shape[1])`
`estimation = EstimationNetwork()`
`gmm = GMM(2,4)`
`net = DAGMM(compression, estimation, gmm)`
`for i in range(0,10):`
    `out = net(train_data[i*80:i*80+80,])`
    `print(out)`
`net.eval()`
`out = net(test_data)`

Thank you once again for the amazing code. It is helping me to understand Pytorch in a better way. :)

**Comment by RomainSabathe** [comment]
Yes, this looks about right! 
Note that this is a very old project that was using Pytorch 0.4.0 at the time, so many things would have changed since then.

**Comment by ajaychawda58** [comment]
Hi Romain, I just have one last question about the code.  As you said, the training happens implicitly. I was unable to find the implementation of DAGMM training objective function as listed in the paper. 
![image](https://user-images.githubusercontent.com/11633476/156344870-497e6214-b74d-430c-b803-13b3ec84716b.png)

Do I need to write this part separately with the training loop? And use a optimizer on this. 

Thank you. :)
